CommonParams:
  circuit_config: /gpfs/bbp.cscs.ch/project/proj64/circuits/O1.v5/20171107/CircuitConfig
  geometry: hex
  n_total_chunks: 10 #  The number of chunks to create when splitting the full sample
  sgid_offset: 1000 # The offset from which to start numbering the fiber IDs
  oversampling: 3.05 # The number of sampled synapse is: expected count * oversampling

FullSample:
  n_slices: -1 #  The number of voxels to sample (-1 = all)


FiberAssignment:
  sigma: 50 # The probability of pairing between a fiber and a synapse is proportional to a gaussian of the distance fiber-synapse parameter. This is its sigma.

ClosestFibersPerVoxel:
  closest_count: 25 # closest_count is the maximum number of the closest fibers to consider for the pairing with a synapse

ChooseConnectionsToKeep:
  cutoff_var: 1.0 # the sigma of the normal cumulative distribution function used for selecting if connections are kept or not

SynapseDensity:
  density_params:
    - low_layer: 4
      low_fraction: 0
      high_layer: 3
      high_fraction: 0.5
      density_profile: [[0.05,0.026], [0.15,0.052], [0.25,0.078], [0.35,0.104], [0.45,0.104], [0.55,0.104], [0.65,0.078], [0.75,0.052], [0.85,0.026], [0.95,0.026]]
    - low_layer: 6
      low_fraction: 0.85
      high_layer: 5
      high_fraction: 0.6
      density_profile: [[0.05,0.013], [0.15,0.026], [0.25,0.039], [0.35,0.052], [0.45,0.0585], [0.55,0.065], [0.65,0.0715], [0.75,0.078], [0.85,0.039], [0.95,0.013]]


WriteNrnH5:
  synapse_type: 120 # excitatory

  # The following parameters are the mean and sigma of the gamma function (np.random.gamma) used
  # to sample the synapse parameters

  # peak synaptic conductance for generalized e-e after PSP scaling 0.792+-0.528 EM
  gsyn_mean: 0.792
  gsyn_sigma: 0.528

  # Analogous to transmitter release probability SR -->
  use_mean: 0.74
  use_sigma: 0.02

  # Time cproj_nrn.h5onstant for recovery from depression SR -->
  D_mean: 671
  D_sigma: 17

  # Time constant for recovery from facilitation SR
  F_mean: 17
  F_sigma: 5

  # decay time constant SR
  DTC_mean: 1.74
  DTC_sigma: 0.2

  # Absolute synaptic efficacy - not used, but a placeholder continuing from legacy nrn.h5 SR
  ASE_mean: 1
  ASE_sigma: 0.01
