#!/usr/bin/env python
import argparse
import logging
import os

from examples.decorators import load_feather

L = logging.getLogger(__name__)


def get_parser():
    '''return the argument parser'''
    parser = argparse.ArgumentParser()

    parser.add_argument('-o', '--output', default='.',
                        help='Output directory')
    parser.add_argument('-v', '--verbose', action='count', dest='verbose', default=0,
                        help='-v for INFO, -vv for DEBUG')
    return parser


def main(args):
    logging.basicConfig(level=(logging.WARNING,
                               logging.INFO,
                               logging.DEBUG)[min(args.verbose, 2)])

    orig_data = ('/gpfs/bbp.cscs.ch/home/gevaert/private/src/'
                 'Projectionizer-v2/old_projections/ncsThalamocortical_VPM_tcS2F_2p6_ps.feather')
    import pandas
    orig_data = pandas.read_feather(orig_data)

    keep_syn_path = os.path.join(output, 'keep_syn.feather')
    keep_syn = load_feather(keep_syn_path)

    create_plots(args.output)


if __name__ == '__main__':
    PARSER = get_parser()
    main(PARSER.parse_args())
