CommonParams:
  circuit_config: /gpfs/bbp.cscs.ch/project/proj64/circuits/S1.v6a/20171124/CircuitConfig
  geometry: s1
  n_total_chunks: 50 #  The number of chunks to create when splitting the full sample
  sgid_offset: 5000000 # The offset from which to start numbering the fiber IDs
  oversampling: 2.6 # The number of sampled synapse is: expected count * oversampling

  # Stuff specific to S1HL
  #voxel_path: /gpfs/bbp.cscs.ch/project/proj64/circuits/S1HL/20171004/.atlas/
  #prefix: C63CB79F-392A-4873-9949-0D347682253A-
  voxel_path: /gpfs/bbp.cscs.ch/project/proj64/circuits/S1.v6/build/.atlas/C63CB79F-392A-4873-9949-0D347682253A/
  prefix: ""

FullSample:
  n_slices: -1 #  The number of voxels to sample (-1 = all)


FiberAssignment:
  sigma: 20 # The probability of pairing between a fiber and a synapse is proportional to a gaussian of the distance fiber-synapse parameter. This is its sigma.

ClosestFibersPerVoxel:
  closest_count: 25 # closest_count is the maximum number of the closest fibers to consider for the pairing with a synapse

ChooseConnectionsToKeep:
  cutoff_var: 1.0 # the sigma of the normal cumulative distribution function used for selecting if connections are kept or not


WriteNrnH5:
  synapse_type: 120 # excitatory

  # The following parameters are the mean and sigma of the gamma function (np.random.gamma) used
  # to sample the synapse parameters

  # peak synaptic conductance for generalized e-e after PSP scaling 0.792+-0.528 EM
  gsyn_mean: 0.792
  gsyn_sigma: 0.528

  # Analogous to transmitter release probability SR -->
  use_mean: 0.75
  use_sigma: 0.02

  # Time cproj_nrn.h5onstant for recovery from depression SR -->
  D_mean: 671
  D_sigma: 17

  # Time constant for recovery from facilitation SR
  F_mean: 17
  F_sigma: 5

  # decay time constant SR
  DTC_mean: 1.74
  DTC_sigma: 0.2

  # Absolute synaptic efficacy - not used, but a placeholder continuing from legacy nrn.h5 SR
  ASE_mean: 1
  ASE_sigma: 0.01
